### ISSUE TITLE
ServerExtMut.xVotingHandler conflict

### ISSUE THREAD

**Issue by g3arshift** [ForrestMarkX/ClassicMode-Issues#5]
### Details
When using ServerExt, specifically ServerExtMut.xVotingHandler, two menus for map and gametype voting appear at the round end screen. One has the correct list of maps and game types, the other only has maps. If I disable ServerExtMut.xVotingHandler, then I can't get any of the other game modes and switch out of ClassicMode.

If I add the other game modes under [KFClassicModeSrv.xVotingHandler] then the game won't switch out of classic mode no matter what is voted for.
### Screenshots
[Screenshot of the problem.](KFMutator.KFMutator_MaxPlayersV2?MaxPlayers=15?MaxMonsters=64)

### Steps to reproduce
Make sure the ServerExtMut.xVotingHandler mutator is active, then reach the end of match voting screen.

**Comment by ForrestMarkX** [comment]
Mod is obviously not compatible with ServerExt and can not be made such due to a engine bug that has been present since Pre-EA
