### ISSUE TITLE
Players disconnect when switching to ClassicMode

### ISSUE THREAD

**Issue by g3arshift** [ForrestMarkX/ClassicMode-Issues#6]
### Details
When switching to ClassicMode from another game mode, my console spits out 

> [0149.85] ScriptLog: Got bad game mode KFClassicModeSrv.KFGameInfo_LegacySurvival expected KFGameContent.KFGameInfo_Survival
[0149.85] DevNet: PreLogin failure: Server No longer available. Mismatch DesiredGameMode.

The screen flashes once with the in game menu as if they're connected before kicking all connected players from the server. They have to reconnect to the server to get back on.

### Screenshots
[Screenshot.](https://i.gyazo.com/e7b9051b406d83c9f839b9e6fa3afe68.png)
### Steps to reproduce
Switch from another gamemode type to ClassicMode at the end of a match.

**Comment by ForrestMarkX** [comment]
Appears to be a bug with GetFullGameModePath, I can't fix this issue from the mod side

**Comment by ForrestMarkX** [comment]
Add this to your config and see if that fixes the issue.

This goes into KFGame.ini
```
[KFClassicModeSrv.KFGameInfo_LegacySurvival]
bEnableGameAnalytics=true
bRecordGameStatsFile=false
MaxPlayers=6
GameModes=(FriendlyName="Survival",ClassNameAndPath="KFClassicModeSrv.KFGameInfo_LegacySurvival",bSoloPlaySupported=True,DifficultyLevels=4,Lengths=4,LocalizeID=0)
GameModes=(FriendlyName="Weekly",ClassNameAndPath="KFGameContent.KFGameInfo_WeeklySurvival",bSoloPlaySupported=True,DifficultyLevels=0,Lengths=0,LocalizeID=1)
GameModes=(FriendlyName="Versus",ClassNameAndPath="KFGameContent.KFGameInfo_VersusSurvival",bSoloPlaySupported=False,DifficultyLevels=0,Lengths=0,LocalizeID=2)
GameModes=(FriendlyName="Endless",ClassNameAndPath="KFGameContent.KFGameInfo_Endless",bSoloPlaySupported=True,DifficultyLevels=4,Lengths=0,LocalizeID=3)
bWaitForNetPlayers=True
bEnableMapObjectives=True
bLogScoring=False
bLogAIDefaults=False
bLogAICount=False
MinNetPlayers=1
EndOfGameDelay=15
ServerExpirationForKillWhenEmpty=120.000000
RequiredMobileInputConfigs=(GroupName="DebugGroup",RequireZoneNames=("DebugStickMoveZone","DebugStickLookZone","DebugLookZone"),bIsAttractModeGroup=False)
bIsStandbyCheckingEnabled=False
GoalScore=0
MaxLives=0
TimeLimit=0
StandbyRxCheatTime=0.000000
StandbyTxCheatTime=0.000000
BadPingThreshold=0
PercentMissingForRxStandby=0.000000
PercentMissingForTxStandby=0.000000
PercentForBadPing=0.000000
JoinInProgressStandbyWaitTime=0.000000
DefaultGameType=KFGameContent.KFGameInfo_Survival
AnimTreePoolSize=0
```

**Comment by g3arshift** [comment]
That's fixed the disconnect issue, thank you.

As a side note, it seems that when alt-tabbing during loading of the gamemode, the camera will end up in strange positions when everything loads back in, and there's no way to access the UI. [Here's what I mean.](https://i.gyazo.com/thumb/1000/d42a5347d533dade2630e99f785d8829-jpg.jpg)

**Comment by ForrestMarkX** [comment]
That's an engine bug that is unfixable from my side
